#sets the minimal percent 
#for fork detecting
:min_percent: 1.99

#time of showing a notification
:time_of_notification: 20

#filters forks which
#cannot be betted(not in breaks etc)
:filtering: true

#notifications with sound
:sound_notification: true

#log mode in default
:log: true

#prints phantomjs logs in STDOUT
:phantomjs_logger: false

#kinds of sport in game
:sport: tennis

#list of bookmakers
:bookmakers:
- WilliamHill
- Marathon
# Parimatch
# Winlinebet
# Betfair
# Sbobet
