---
:min_percent: 1.3
:task: /home/gentoo/Temp/task.iim
:waiter: /home/gentoo/Temp/waiter.iim
:macros_folder: /home/gentoo/Temp/
:log_forks: /home/gentoo/Temp/ffff
:log_parsed_bookies: /home/gentoo/Temp/kkkk
:log_thrown_forks: /home/gentoo/Temp/tttt
:filtering: true
:bookies:
- Marathon
- Betfair
- WilliamHill
