---
:min_percent: 1.3
:task: /home/gentoo/Temp/task.iim
:waiter: /home/gentoo/Temp/waiter.iim
:macros_folder: /home/gentoo/Temp/
:log_file: /home/gentoo/Temp/forker_log
:filtering: true
:bookies:
- Marathon
- Betfair
- WilliamHill
