require 'forker/version.rb'
require 'forker/downloader.rb'
require 'forker/eventsfinder.rb'
require 'forker/forksfinder.rb'
require 'forker/comparer.rb'
require 'forker/output.rb'
require 'forker/williamhill.rb'
require 'forker/betfair.rb'
require 'forker/marathon.rb'
require 'forker/parimatch.rb'
require 'forker/sbobet.rb'
require 'forker/winlinebet.rb'
require 'forker/names_winlinebet.rb'
require 'capybara/poltergeist'
require 'yaml'
require 'nokogiri'
require 'mechanize'

module Forker
  MARATHON_BASE_ADDRESS = 'https://www.mirrormarafonbet.com/en/'
  MARATHON_TENNIS_LIVE_PAGE_ADDRESS = MARATHON_BASE_ADDRESS + 'live/22723'
  WILLIAMHILL_BASE_ADDRESS = 'http://sports.bukstavki77.com/bet/en-ie/'
  WILLIAMHILL_LIVE_PAGE_ADDRESS = WILLIAMHILL_BASE_ADDRESS + 'betlive/all'
end
